//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildingsRegistry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class buildings
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public buildings()
        {
            this.servicesAssigned = new HashSet<servicesAssigned>();
        }
    
        public int Id { get; set; }
        public string BuildingName { get; set; }
        public Nullable<int> Capacity { get; set; }
        public Nullable<int> ProvinceCode { get; set; }
        public Nullable<int> CantonCode { get; set; }
        public Nullable<int> AreaCode { get; set; }
        public Nullable<int> PropertyStatus { get; set; }
        public Nullable<System.DateTime> Expiration { get; set; }
    
        public virtual propertyStatus propertyStatus1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<servicesAssigned> servicesAssigned { get; set; }
    }
}
