//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildingsRegistry.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class buildings_registryEntities : DbContext
    {
        public buildings_registryEntities()
            : base("name=buildings_registryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<area> area { get; set; }
        public virtual DbSet<buildings> buildings { get; set; }
        public virtual DbSet<canton> canton { get; set; }
        public virtual DbSet<propertyStatus> propertyStatus { get; set; }
        public virtual DbSet<province> province { get; set; }
        public virtual DbSet<publicServices> publicServices { get; set; }
        public virtual DbSet<servicesAssigned> servicesAssigned { get; set; }
        public virtual DbSet<serviceType> serviceType { get; set; }
        public virtual DbSet<unit> unit { get; set; }
    }
}
