//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildingsRegistry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class province
    {
        public int Id { get; set; }
        public Nullable<int> ProvinceCode { get; set; }
        public string ProvinceName { get; set; }
    }
}
